### ISSUE TITLE
Word2vec installation problems

### ISSUE THREAD

**Issue by SomeoneNotLikeYou** [cuhksz-nlp/SANER#13]
我直接pip install word2vec 提示信息为
ERROR: Could not build wheels for word2vec which use PEP 517 and cannot be installed directly

我转而使用from gensim.models import Word2Vec
仍然报错
Traceback (most recent call last):
File "E:/aDemo/NamedEntityRecognition/1_code/pytorch/6-SANER-master/train_zen_cn.py", line 157, in
data_bundle, embed, bi_embed, train_feature_data, dev_feature_data, test_feature_data, feature2id, id2feature = load_data()
File "E:\aDemo\NamedEntityRecognition\1_code\pytorch\6-SANER-master\fastNLP\core\utils.py", line 155, in wrapper
results = func(*args, **kwargs)
File "E:/aDemo/NamedEntityRecognition/1_code/pytorch/6-SANER-master/train_zen_cn.py", line 128, in load_data
data_bundle.get_vocab('chars').word2idx, glove_path, dict_save_path
File "E:\aDemo\NamedEntityRecognition\1_code\pytorch\6-SANER-master\get_context.py", line 11, in get_neighbor_for_vocab
model = word2vec.load(dataPath)
File "E:\software\Anaconda\envs\py36gpu\lib\site-packages\gensim\models\word2vec.py", line 1330, in load
model = super(Word2Vec, cls).load(*args, **kwargs)
File "E:\software\Anaconda\envs\py36gpu\lib\site-packages\gensim\models\base_any2vec.py", line 1244, in load
model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
File "E:\software\Anaconda\envs\py36gpu\lib\site-packages\gensim\models\base_any2vec.py", line 603, in load
return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
File "E:\software\Anaconda\envs\py36gpu\lib\site-packages\gensim\utils.py", line 426, in load
obj = unpickle(fname)
File "E:\software\Anaconda\envs\py36gpu\lib\site-packages\gensim\utils.py", line 1384, in unpickle
return _pickle.load(f, encoding='latin1')
__pickle.UnpicklingError: unpickling stack underflow_

- [ ]

**Comment by SomeoneNotLikeYou** [comment]
conda install -c anaconda word2vec  安装0.9.4的word2vec    就可以了
直接安装pip install word2vec 0.11.1会报错不知道为什么   

运行阶段出现了一个问题 ValueError: Cannot recognize data/gigaword_chn.all.a2b.uni.ite50.vec. 
我需要把这个词典导进去吗

**Comment by nyy477** [comment]
hello，同学，你需要在这里下载对应的预训练embedding并把其放在data目录下：https://pan.baidu.com/s/1pLO6T9D
