### ISSUE TITLE
number in weiboNER_2nd_conll.train

### ISSUE THREAD

**Issue by tyistyler** [cuhksz-nlp/SANER#4]
all datas in weibo(ex: weiboNER_2nd_conll.train) has num after char, "朋0 友1"....“...A7 p8 p9 S10 t11 o12 r13 e14”， while  the data preprocessed is ""朋 友"....“..."A p p S1 t1 o1 r1 e1"  ,maybe it has some influence about results..

**Comment by tyistyler** [comment]
and could you release the code to do test, maybe i write the wrong code and return that:
thanks!!!

-----------------------------------------------------------------
Traceback (most recent call last):
  File "train_zen_cn.py", line 236, in <module>
    trainer.train(load_best_model=True)
  File "/content/drive/My Drive/NER/SANER/fastNLP/core/trainer.py", line 705, in train
    load_succeed = self._load_model(self.model, model_name)
  File "/content/drive/My Drive/NER/SANER/fastNLP/core/trainer.py", line 970, in _load_model
    model.load_state_dict(states)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TENER:
	size mismatch for embed.embeds.0.embedding.weight: copying a param with shape torch.Size([3208, 200]) from checkpoint, the shape in current model is torch.Size([2565, 200]).
	size mismatch for bi_embed.embedding.weight: copying a param with shape torch.Size([36883, 50]) from checkpoint, the shape in current model is torch.Size([15798, 50]).
